### ISSUE TITLE
simple_por is not LVS clean

### ISSUE THREAD

**Issue by marwaneltoukhy** [efabless/caravel-gf180mcu#79]
simple_por is not LVS clea, maybe it needs to be redone using the new PDK? Attached the output of netgen.

[simple_por.txt](https://github.com/efabless/caravel-gf180mcu/files/10155551/simple_por.txt)
circuit 1: extracted gds from `caravel-gf180mcu/macros/simple_por/gds/simple_por.gds`
circuit 2: spice from `caravel-gf180mcu/macros/simple_por/netlist/simple_por.spice`

**Comment by RTimothyEdwards** [comment]
Magic GDS import error.  It works correctly when extracted from .mag, and the GDS is correct.  The MiM cap contacts are getting lost when reading the GDS back into magic.  I will fix it.

**Comment by RTimothyEdwards** [comment]
This was fixed in magic for the LVS flow through netgen;  however, the `simple_por` circuit has remained not LVS clean when using Calibre.  I tracked this down to a requirement for the capacitor length marker and added it to the `simple_por` GDS file in pull request #168.

@marwaneltoukhy :  Please check that the `simple_por` can be checked to the transistor level after merging #168 and is LVS clean in Calibre.  If so, this ticket can be closed.
